name: Pull Changes to GCP Compute Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy Repository Changes
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.GCP_INSTANCE_IP }}
        username: 106725524452792835454
        key: ${{ secrets.GCP_SSH_KEY }}
        port: 22
        source: "."
        target: "https://console.cloud.google.com/compute/instances?project=test-mlops-deploy"

    - name: Pull Changes on GCP Instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCP_INSTANCE_IP }}
        username: 106725524452792835454
        key: ${{ secrets.GCP_SSH_KEY }}
        port: 22
        script: "https://github.com/Naveen2627-hub/FakeJobPosting.git"
