name: Deploy to Google Compute Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        export_default_credentials: true

    - name: Install Dependencies
      run: | # Add commands to install dependencies, if needed
        echo "Optionally, install any dependencies here."

    - name: Deploy to GCE
      run: |
        # Example: Copy files to the instance. Adjust the scp/ssh commands according to your needs.
        gcloud compute scp ./ ${{ secrets.GCE_INSTANCE }}:~/app --zone ${{ secrets.GCE_ZONE }} --recurse
        # SSH command to restart your application or run deployment scripts on your instance
        gcloud compute ssh ${{ secrets.GCE_INSTANCE }} --zone ${{ secrets.GCE_ZONE }} --command "cd ~/app && ./deploy_script.sh"
